"""Emit a Markdown confidence heatmap across the v0.5 cohort × 11 dimensions.

Reads evaluations/<lang>.yaml for cohort languages, extracts the confidence
value (low/medium/high) per dimension, and writes a Markdown table to
outputs/confidence-heatmap.md.

Visual scan: glyph ● high, ◐ medium, ○ low.
"""
from datetime import date
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
EVAL_DIR = ROOT / "evaluations"
OUT_PATH = ROOT / "outputs" / "confidence-heatmap.md"

COHORT_ORDER = [
    "go", "typescript", "dotnet", "kotlin", "rust",
    "python", "swift", "java", "elixir", "cpp",
]

DIMENSIONS = [
    ("human_cognition", "HC"),
    ("machine_cognition", "MC"),
    ("ai_agent_operability", "AO"),
    ("runtime_ecosystem", "RE"),
    ("strategic_viability", "SV"),
    ("ai_systems_native", "AIN"),
    ("ai_systems_ecosystem", "AIE"),
    ("structured_output_native", "SON"),
    ("structured_output_ecosystem", "SOE"),
    ("ecosystem_dependency_risk", "EDR"),
    ("reachability_to_top_tier", "RCH"),
]

DISPLAY_NAMES = {
    "typescript": "TypeScript",
    "python": "Python",
    "go": "Go",
    "dotnet": ".NET (C#)",
    "rust": "Rust",
    "kotlin": "Kotlin",
    "java": "Java",
    "elixir": "Elixir",
    "swift": "Swift",
    "cpp": "C++",
}

GLYPH = {
    "high": "● high",
    "medium": "◐ med",
    "low": "○ low",
}


def load_confidence(lang: str) -> dict[str, str]:
    path = EVAL_DIR / f"{lang}.yaml"
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    scores = data.get("scores", {}) or {}
    return {
        dim: (scores.get(dim, {}) or {}).get("confidence", "?")
        for dim, _ in DIMENSIONS
    }


def render_table(rows: dict[str, dict[str, str]]) -> str:
    header = "| Language | " + " | ".join(short for _, short in DIMENSIONS) + " |"
    separator = "|---|" + "|".join(":---:" for _ in DIMENSIONS) + "|"
    body_lines = []
    for lang in COHORT_ORDER:
        cells = [
            GLYPH.get(rows[lang].get(dim, "?"), rows[lang].get(dim, "?"))
            for dim, _ in DIMENSIONS
        ]
        body_lines.append(f"| {DISPLAY_NAMES[lang]} | " + " | ".join(cells) + " |")
    return "\n".join([header, separator, *body_lines])


def count_low(rows):
    return sum(1 for lang in rows for v in rows[lang].values() if v == "low")


def count_medium(rows):
    return sum(1 for lang in rows for v in rows[lang].values() if v == "medium")


def count_high(rows):
    return sum(1 for lang in rows for v in rows[lang].values() if v == "high")


def main() -> None:
    rows = {lang: load_confidence(lang) for lang in COHORT_ORDER}
    table = render_table(rows)

    n_high = count_high(rows)
    n_medium = count_medium(rows)
    n_low = count_low(rows)
    total = n_high + n_medium + n_low

    output = f"""# Confidence Heatmap — Framework v0.5

*Generated by `scripts/confidence_heatmap.py` on {date.today().isoformat()}.*

Confidence is the rater's degree of certainty in each (language × dimension) score, set when the evaluation YAML was authored. **High** means the score is well-anchored in primary sources and would be unlikely to move on review; **medium** means the score is anchored but could move 0.5; **low** means the score depends on judgment that another rater could reasonably challenge.

Cohort: 10 languages × 11 dimensions = {total} cells.

- High confidence: {n_high} cells ({n_high / total:.0%})
- Medium confidence: {n_medium} cells ({n_medium / total:.0%})
- Low confidence: {n_low} cells ({n_low / total:.0%})

## Heatmap

{table}

**Dimension keys:** HC = Human Cognition · MC = Machine Cognition · AO = AI-Agent Operability · RE = Runtime/Ecosystem · SV = Strategic Viability · AIN = AI-systems native · AIE = AI-systems ecosystem · SON = Structured-output native · SOE = Structured-output ecosystem · EDR = Ecosystem dependency risk · RCH = Reachability to top tier.

## How to read this

A row of high-confidence cells means the language's evaluation is well-anchored. A row with multiple medium cells indicates dimensions where another rater could reasonably arrive at a half-point different score. Low-confidence cells mark places where the framework's evidence base is thinnest and where additional source work would have the most leverage.

The matrix in `comparisons/overview.md` and the per-language scores in `evaluations/<lang>.yaml` are the upstream source. Re-run this script after any score change to refresh the heatmap.
"""
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(output, encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT).as_posix()}")
    print(f"  high={n_high} medium={n_medium} low={n_low} total={total}")


if __name__ == "__main__":
    main()
